# -*- coding: utf-8 -*-
"""Task 2 - M1 c.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBqOFpjbggIXt3hFUO57zuQo3hQaKqTO

### Polars Script Overview

This script performs the same analysis as the Pure Python and Pandas versions, but uses the Polars library for faster and more efficient data processing. It reads the CSV dataset, handles malformed rows, and converts mixed data types (including range-based values) into usable formats.

The script computes dataset-level and column-level statistics, including numeric metrics (mean, min, max, standard deviation, median) and categorical summaries (unique values, mode, and top frequencies). It also performs grouped analysis by relevant keys such as page_id and page_id + ad_id, allowing comparison of patterns across different entities.

Polars is optimized for performance, so this implementation demonstrates how the same analysis can be executed more efficiently while maintaining the same logic and results as the previous scripts.
"""

# Polars Descriptive Statistics + Grouped Analysis
# This script analyzes CSV datasets using Polars.
# It safely handles malformed CSV rows, mixed data types, missing values,
# dictionary-like range values, and grouped analysis.

!pip install polars -q

import polars as pl
import csv
import ast
import os
import time

# =========================
# CONFIG
# =========================

INPUT_FILE = "/content/2024_fb_ads_president_scored_anon.csv"  # change if needed
MAX_GROUPS_TO_DISPLAY = 3
TOP_N_VALUES = 5
DIVIDER = "-" * 80


# =========================
# HELPER FUNCTIONS
# =========================

def is_missing_value(value):
    if value is None:
        return True
    text = str(value).strip()
    return text in ["", "nan", "NaN", "None", "N/A", "NA", "null", "NULL"]


def parse_range_value(value):
    if is_missing_value(value):
        return None

    text = str(value).strip()

    try:
        return float(
            text.replace(",", "")
                .replace("$", "")
                .replace("%", "")
        )
    except:
        pass

    if not (text.startswith("{") and text.endswith("}")):
        return None

    try:
        parsed = ast.literal_eval(text)

        if not isinstance(parsed, dict):
            return None

        lower = parsed.get("lower_bound")
        upper = parsed.get("upper_bound")

        lower = float(str(lower).replace(",", "")) if lower not in [None, ""] else None
        upper = float(str(upper).replace(",", "")) if upper not in [None, ""] else None

        if lower is not None and upper is not None:
            return (lower + upper) / 2
        elif lower is not None:
            return lower
        else:
            return None

    except:
        return None


def convert_column_to_numeric(df, col):
    values = df[col].to_list()
    numeric_values = [parse_range_value(v) for v in values]
    return pl.Series(col, numeric_values, dtype=pl.Float64)


def infer_column_types(df):
    column_types = {}

    for col in df.columns:
        values = df[col].to_list()
        non_missing = [v for v in values if not is_missing_value(v)]

        if len(non_missing) == 0:
            column_types[col] = "unknown"
            continue

        numeric_values = [parse_range_value(v) for v in non_missing]
        numeric_count = sum(v is not None for v in numeric_values)
        numeric_ratio = numeric_count / len(non_missing)

        if numeric_ratio >= 0.80:
            column_types[col] = "numeric"
        else:
            column_types[col] = "categorical"

    return column_types


def choose_grouping_columns(df):
    cols = set(df.columns)
    groupings = []

    if "page_id" in cols:
        groupings.append(["page_id"])

    if "page_id" in cols and "ad_id" in cols:
        groupings.append(["page_id", "ad_id"])

    if "page_id" in cols and "post_id" in cols:
        groupings.append(["page_id", "post_id"])

    if "account_id" in cols:
        groupings.append(["account_id"])
    elif "author_id" in cols:
        groupings.append(["author_id"])
    elif "username" in cols:
        groupings.append(["username"])
    elif "handle" in cols:
        groupings.append(["handle"])

    unique_groupings = []
    for grouping in groupings:
        if grouping not in unique_groupings:
            unique_groupings.append(grouping)

    return unique_groupings


# =========================
# SAFE CSV READER
# =========================

def read_csv_with_python_then_polars(file_path):
    """
    Reads the CSV using Python's csv module first.
    Every value is forced to string before creating a Polars DataFrame.
    This avoids Polars schema inference errors from mixed-type columns.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    rows = []
    skipped_rows = 0

    with open(file_path, "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        fieldnames = reader.fieldnames

        if fieldnames is None:
            raise ValueError("CSV file has no header row.")

        for row in reader:
            try:
                clean_row = {}

                for col in fieldnames:
                    value = row.get(col, "")
                    clean_row[col] = "" if value is None else str(value)

                rows.append(clean_row)

            except:
                skipped_rows += 1

    print("CSV loaded using Python csv module, then converted to Polars.")
    print(f"Rows skipped during safe loading: {skipped_rows:,}")

    columns_dict = {}

    for col in fieldnames:
        columns_dict[col] = [row.get(col, "") for row in rows]

    df = pl.DataFrame(columns_dict, schema={col: pl.String for col in fieldnames})

    return df


# =========================
# DATASET SUMMARY
# =========================

def print_dataset_summary(df, column_types):
    print("\n" + DIVIDER)
    print("DATASET OVERALL SUMMARY")
    print(DIVIDER)

    print(f"Row count    : {df.height:,}")
    print(f"Column count : {df.width:,}")

    print("\nMissing values per column:")
    for col in df.columns:
        values = df[col].to_list()
        missing = sum(is_missing_value(v) for v in values)
        pct = missing / df.height * 100 if df.height else 0
        print(f"  {col:<45} {missing:>8,} ({pct:5.1f}%)")

    print("\nInferred data types:")
    for col in df.columns:
        print(f"  {col:<45} {column_types[col]}")


# =========================
# COLUMN-LEVEL STATS
# =========================

def print_numeric_stats(df, col, indent=""):
    numeric_series = convert_column_to_numeric(df, col).drop_nulls()

    print(f"\n{indent}{col} [numeric]")

    if numeric_series.len() == 0:
        print(f"{indent}  No valid numeric values.")
        return

    missing = df.height - numeric_series.len()

    print(f"{indent}  count   : {numeric_series.len():,}")
    print(f"{indent}  missing : {missing:,}")
    print(f"{indent}  mean    : {numeric_series.mean():,.2f}")
    print(f"{indent}  min     : {numeric_series.min():,.2f}")
    print(f"{indent}  max     : {numeric_series.max():,.2f}")
    print(f"{indent}  std dev : {numeric_series.std(ddof=0):,.2f}")
    print(f"{indent}  median  : {numeric_series.median():,.2f}")


def print_categorical_stats(df, col, indent=""):
    values = df[col].to_list()
    clean_values = [str(v).strip() for v in values if not is_missing_value(v)]

    print(f"\n{indent}{col} [categorical]")
    print(f"{indent}  count          : {len(clean_values):,}")
    print(f"{indent}  missing        : {df.height - len(clean_values):,}")
    print(f"{indent}  unique values  : {len(set(clean_values)):,}")

    if len(clean_values) == 0:
        print(f"{indent}  mode           : N/A")
        print(f"{indent}  mode frequency : 0")
        return

    value_counts = (
        pl.DataFrame({col: clean_values})
        .group_by(col)
        .len()
        .sort("len", descending=True)
    )

    mode_value = value_counts[col][0]
    mode_frequency = value_counts["len"][0]

    print(f"{indent}  mode           : {mode_value}")
    print(f"{indent}  mode frequency : {mode_frequency:,}")
    print(f"{indent}  top 5 values   :")

    top_values = value_counts.head(TOP_N_VALUES)

    for row in top_values.iter_rows(named=True):
        value = str(row[col])
        count = row["len"]

        if len(value) > 65:
            value = value[:62] + "..."

        print(f"{indent}    {value:<65} {count:,}")


def print_column_statistics(df, column_types):
    print("\n" + DIVIDER)
    print("COLUMN-LEVEL STATISTICS")
    print(DIVIDER)

    for col in df.columns:
        if column_types[col] == "numeric":
            print_numeric_stats(df, col)
        else:
            print_categorical_stats(df, col)


# =========================
# POLARS DESCRIBE
# =========================

def print_polars_describe(df, column_types):
    print("\n" + DIVIDER)
    print("POLARS DESCRIBE OUTPUT")
    print(DIVIDER)

    numeric_columns = []

    for col in df.columns:
        if column_types[col] == "numeric":
            numeric_columns.append(convert_column_to_numeric(df, col))

    if numeric_columns:
        numeric_df = pl.DataFrame(numeric_columns)
        print("\nNumeric describe:")
        print(numeric_df.describe())
    else:
        print("\nNo numeric columns found.")

    categorical_cols = [col for col in df.columns if column_types[col] != "numeric"]

    if categorical_cols:
        print("\nCategorical describe:")
        print(df.select(categorical_cols).describe())
    else:
        print("\nNo categorical columns found.")


# =========================
# GROUPED ANALYSIS
# =========================

def print_grouped_analysis(df, group_cols, column_types):
    print("\n" + DIVIDER)
    print(f"GROUPED ANALYSIS BY: {', '.join(group_cols)}")
    print(DIVIDER)

    for col in group_cols:
        if col not in df.columns:
            print(f"Skipping group because missing column: {col}")
            return

    group_sizes = (
        df.group_by(group_cols)
        .len()
        .sort("len", descending=True)
    )

    print(f"Total groups found: {group_sizes.height:,}")

    print("\nTop groups by row count:")
    print(group_sizes.head(10))

    print(f"\nShowing detailed statistics for top {MAX_GROUPS_TO_DISPLAY} groups only.")

    top_groups = group_sizes.head(MAX_GROUPS_TO_DISPLAY)

    for row in top_groups.iter_rows(named=True):
        group_filter = None

        for col in group_cols:
            condition = pl.col(col) == row[col]
            group_filter = condition if group_filter is None else group_filter & condition

        group_df = df.filter(group_filter)

        if len(group_cols) == 1:
            group_name = row[group_cols[0]]
        else:
            group_name = tuple(row[col] for col in group_cols)

        print("\n" + "=" * 70)
        print(f"GROUP: {group_name}")
        print(f"ROWS : {group_df.height:,}")
        print("=" * 70)

        for col in df.columns:
            if column_types[col] == "numeric":
                print_numeric_stats(group_df, col, indent="  ")
            else:
                print_categorical_stats(group_df, col, indent="  ")


# =========================
# MAIN
# =========================

def run_polars_analysis(file_path):
    start_time = time.time()

    print("\n" + "=" * 80)
    print("POLARS DESCRIPTIVE STATISTICS + GROUPED ANALYSIS")
    print("=" * 80)
    print(f"Input file: {file_path}")

    df = read_csv_with_python_then_polars(file_path)

    print(f"Loaded rows   : {df.height:,}")
    print(f"Loaded columns: {df.width:,}")

    column_types = infer_column_types(df)

    print_dataset_summary(df, column_types)
    print_column_statistics(df, column_types)
    print_polars_describe(df, column_types)

    groupings = choose_grouping_columns(df)

    if groupings:
        for group_cols in groupings:
            print_grouped_analysis(df, group_cols, column_types)
    else:
        print("\nNo sensible grouping columns found for this dataset.")

    end_time = time.time()

    print("\n" + "=" * 80)
    print("POLARS ANALYSIS COMPLETE")
    print(f"Runtime: {end_time - start_time:.2f} seconds")
    print("=" * 80)


# =========================
# RUN
# =========================

run_polars_analysis(INPUT_FILE)