# -*- coding: utf-8 -*-
"""Task 2- M1 A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vik1TMbYSx8764tb10S7VSqDtb-Jzu1c

###  Pure Python Descriptive Statistics + Grouped Analysis
This script analyzes a CSV dataset using only Python standard libraries.
It computes dataset-level and column-level statistics, including:
 - Numeric: count, mean, min, max, standard deviation, median
 - Categorical: count, unique values, mode, top frequencies
 It also performs grouped analysis by page_id and (page_id, ad_id)
 using dictionary-based grouping to replicate how Pandas groupby works.
"""

# ============================================================
# Script 1: Pure Python Descriptive Statistics + Grouped Analysis
# No third-party libraries
# ============================================================

import csv
import math
import os
import collections
import ast
import time


# =========================
# CONFIG
# =========================

INPUT_FILE = "/content/2024_fb_ads_president_scored_anon.csv"   # <-- CHANGE this to your uploaded CSV filename
MAX_GROUPS_TO_DISPLAY = 5
TOP_N_VALUES = 5
NUMERIC_THRESHOLD = 0.80
DIVIDER = "-" * 80


# =========================
# HELPER FUNCTIONS
# =========================

def is_missing(value):
    if value is None:
        return True
    text = str(value).strip()
    return text in ("", "nan", "NaN", "None", "N/A", "NA", "null", "NULL")


def clean_number_text(value):
    return (
        str(value)
        .strip()
        .replace(",", "")
        .replace("$", "")
        .replace("%", "")
    )


def to_float_safe(value):
    if is_missing(value):
        return None, False

    text = clean_number_text(value)

    try:
        return float(text), True
    except ValueError:
        return None, False


def try_parse_range(value):
    """
    Handles values like:
    {'lower_bound': '100', 'upper_bound': '199'}

    Returns midpoint if parseable.
    Otherwise returns None.
    """
    if is_missing(value):
        return None

    text = str(value).strip()

    if not (text.startswith("{") and text.endswith("}")):
        return None

    try:
        parsed = ast.literal_eval(text)
        if not isinstance(parsed, dict):
            return None

        lower, lower_ok = to_float_safe(parsed.get("lower_bound"))
        upper, upper_ok = to_float_safe(parsed.get("upper_bound"))

        if lower_ok and upper_ok:
            return (lower + upper) / 2
        elif lower_ok:
            return lower
        else:
            return None

    except Exception:
        return None


def value_to_numeric(value):
    """
    Converts simple numeric values and dict-range values to numeric.
    """
    num, ok = to_float_safe(value)
    if ok:
        return num, True

    range_num = try_parse_range(value)
    if range_num is not None:
        return range_num, True

    return None, False


# =========================
# STATISTICS FUNCTIONS
# =========================

def mean(numbers):
    return sum(numbers) / len(numbers) if numbers else None


def std_dev(numbers):
    """
    Population standard deviation.
    """
    if len(numbers) < 2:
        return None

    avg = mean(numbers)
    variance = sum((x - avg) ** 2 for x in numbers) / len(numbers)
    return math.sqrt(variance)


def median(numbers):
    if not numbers:
        return None

    sorted_nums = sorted(numbers)
    n = len(sorted_nums)
    mid = n // 2

    if n % 2 == 1:
        return sorted_nums[mid]
    else:
        return (sorted_nums[mid - 1] + sorted_nums[mid]) / 2


def summarize_numeric(values):
    nums = []
    missing = 0

    for value in values:
        num, ok = value_to_numeric(value)
        if ok:
            nums.append(num)
        else:
            missing += 1

    if not nums:
        return {
            "type": "numeric",
            "count": 0,
            "missing": missing,
            "mean": None,
            "min": None,
            "max": None,
            "std_dev": None,
            "median": None
        }

    return {
        "type": "numeric",
        "count": len(nums),
        "missing": missing,
        "mean": mean(nums),
        "min": min(nums),
        "max": max(nums),
        "std_dev": std_dev(nums),
        "median": median(nums)
    }


def summarize_categorical(values, top_n=5):
    cleaned = []
    missing = 0

    for value in values:
        if is_missing(value):
            missing += 1
        else:
            cleaned.append(str(value).strip())

    counter = collections.Counter(cleaned)
    top_values = counter.most_common(top_n)

    if top_values:
        mode_value, mode_freq = top_values[0]
    else:
        mode_value, mode_freq = None, 0

    return {
        "type": "categorical",
        "count": len(cleaned),
        "missing": missing,
        "unique_count": len(counter),
        "mode": mode_value,
        "mode_frequency": mode_freq,
        "top_5_values": top_values
    }


def infer_column_type(values, sample_size=1000, threshold=0.80):
    checked = 0
    numeric_count = 0

    for value in values:
        if is_missing(value):
            continue

        checked += 1
        _, ok = value_to_numeric(value)

        if ok:
            numeric_count += 1

        if checked >= sample_size:
            break

    if checked == 0:
        return "unknown"

    numeric_ratio = numeric_count / checked

    if numeric_ratio >= threshold:
        return "numeric"
    else:
        return "categorical"


# =========================
# READING DATA
# =========================

def read_csv_dataset(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    rows = []
    columns_data = collections.OrderedDict()

    with open(file_path, "r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        column_names = reader.fieldnames or []

        for col in column_names:
            columns_data[col] = []

        for row in reader:
            rows.append(row)

            for col in column_names:
                columns_data[col].append(row.get(col, ""))

    return rows, column_names, columns_data


# =========================
# DISPLAY FUNCTIONS
# =========================

def format_number(value, decimals=2):
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:,.{decimals}f}"
    return str(value)


def print_dataset_summary(rows, column_names, columns_data, column_types):
    print("\n" + DIVIDER)
    print("DATASET OVERALL SUMMARY")
    print(DIVIDER)

    print(f"Row count    : {len(rows):,}")
    print(f"Column count : {len(column_names):,}")

    print("\nMissing values per column:")
    for col in column_names:
        missing = sum(1 for value in columns_data[col] if is_missing(value))
        pct = (missing / len(rows) * 100) if rows else 0
        print(f"  {col:<40} {missing:>8,}  ({pct:5.1f}%)")

    print("\nInferred data types:")
    for col in column_names:
        print(f"  {col:<40} {column_types[col]}")


def print_numeric_stats(col, stats, indent=""):
    print(f"{indent}{col} [numeric]")
    print(f"{indent}  count   : {stats['count']:,}")
    print(f"{indent}  missing : {stats['missing']:,}")
    print(f"{indent}  mean    : {format_number(stats['mean'])}")
    print(f"{indent}  min     : {format_number(stats['min'])}")
    print(f"{indent}  max     : {format_number(stats['max'])}")
    print(f"{indent}  std dev : {format_number(stats['std_dev'])}")
    print(f"{indent}  median  : {format_number(stats['median'])}")


def print_categorical_stats(col, stats, indent=""):
    print(f"{indent}{col} [categorical]")
    print(f"{indent}  count          : {stats['count']:,}")
    print(f"{indent}  missing        : {stats['missing']:,}")
    print(f"{indent}  unique values  : {stats['unique_count']:,}")
    print(f"{indent}  mode           : {stats['mode']}")
    print(f"{indent}  mode frequency : {stats['mode_frequency']:,}")
    print(f"{indent}  top 5 values   :")

    for value, freq in stats["top_5_values"]:
        short_value = str(value)
        if len(short_value) > 60:
            short_value = short_value[:57] + "..."
        print(f"{indent}    {short_value:<60} {freq:,}")


def print_column_statistics(column_names, columns_data, column_types):
    print("\n" + DIVIDER)
    print("COLUMN-LEVEL STATISTICS")
    print(DIVIDER)

    for col in column_names:
        print("\n" + "-" * 60)

        if column_types[col] == "numeric":
            stats = summarize_numeric(columns_data[col])
            print_numeric_stats(col, stats)
        else:
            stats = summarize_categorical(columns_data[col], TOP_N_VALUES)
            print_categorical_stats(col, stats)


# =========================
# GROUPING FUNCTIONS
# =========================

def group_rows(rows, group_columns):
    """
    Creates dictionary:
    {
        group_key: [row1, row2, row3]
    }
    """
    groups = collections.defaultdict(list)

    for row in rows:
        key_parts = []

        for col in group_columns:
            key_parts.append(row.get(col, ""))

        if len(key_parts) == 1:
            group_key = key_parts[0]
        else:
            group_key = tuple(key_parts)

        groups[group_key].append(row)

    return groups


def rows_to_columns(group_rows_list, column_names):
    group_columns_data = collections.OrderedDict()

    for col in column_names:
        group_columns_data[col] = []

    for row in group_rows_list:
        for col in column_names:
            group_columns_data[col].append(row.get(col, ""))

    return group_columns_data


def summarize_group(group_rows_list, column_names):
    group_columns_data = rows_to_columns(group_rows_list, column_names)

    group_column_types = {}
    group_summary = {}

    for col in column_names:
        col_type = infer_column_type(group_columns_data[col])
        group_column_types[col] = col_type

        if col_type == "numeric":
            group_summary[col] = summarize_numeric(group_columns_data[col])
        else:
            group_summary[col] = summarize_categorical(group_columns_data[col], TOP_N_VALUES)

    return group_summary, group_column_types


def print_grouped_analysis(rows, column_names, group_columns, max_groups=5):
    print("\n" + DIVIDER)
    print(f"GROUPED ANALYSIS BY: {', '.join(group_columns)}")
    print(DIVIDER)

    missing_group_cols = [col for col in group_columns if col not in column_names]

    if missing_group_cols:
        print(f"Cannot group because these columns are missing: {missing_group_cols}")
        return

    groups = group_rows(rows, group_columns)

    print(f"Total groups found: {len(groups):,}")

    group_sizes = []
    for key, group in groups.items():
        group_sizes.append((key, len(group)))

    group_sizes = sorted(group_sizes, key=lambda x: x[1], reverse=True)

    print("\nTop groups by row count:")
    for key, size in group_sizes[:10]:
        print(f"  {key}: {size:,} rows")

    print(f"\nShowing detailed statistics for top {max_groups} groups only.")

    for group_key, group_size in group_sizes[:max_groups]:
        group_data = groups[group_key]

        print("\n" + "=" * 70)
        print(f"GROUP: {group_key}")
        print(f"ROWS : {group_size:,}")
        print("=" * 70)

        group_summary, _ = summarize_group(group_data, column_names)

        for col in column_names:
            print("\n" + "-" * 50)

            stats = group_summary[col]

            if stats["type"] == "numeric":
                print_numeric_stats(col, stats, indent="  ")
            else:
                print_categorical_stats(col, stats, indent="  ")


# =========================
# MAIN ANALYSIS
# =========================

def run_analysis(file_path):
    start_time = time.time()

    print("\n" + "=" * 80)
    print("PURE PYTHON DESCRIPTIVE STATISTICS")
    print("No Pandas, No NumPy, No Third-Party Libraries")
    print("=" * 80)
    print(f"Input file: {file_path}")

    rows, column_names, columns_data = read_csv_dataset(file_path)

    column_types = {}

    for col in column_names:
        column_types[col] = infer_column_type(
            columns_data[col],
            threshold=NUMERIC_THRESHOLD
        )

    print_dataset_summary(rows, column_names, columns_data, column_types)

    print_column_statistics(column_names, columns_data, column_types)

    # Required grouped analysis 1: page_id
    if "page_id" in column_names:
        print_grouped_analysis(
            rows=rows,
            column_names=column_names,
            group_columns=["page_id"],
            max_groups=MAX_GROUPS_TO_DISPLAY
        )
    else:
        print("\npage_id column not found. Skipping page_id grouped analysis.")

    # Required grouped analysis 2: page_id + ad_id
    if "page_id" in column_names and "ad_id" in column_names:
        print_grouped_analysis(
            rows=rows,
            column_names=column_names,
            group_columns=["page_id", "ad_id"],
            max_groups=MAX_GROUPS_TO_DISPLAY
        )
    else:
        print("\npage_id/ad_id columns not found. Skipping combined grouped analysis.")

    end_time = time.time()

    print("\n" + "=" * 80)
    print("ANALYSIS COMPLETE")
    print(f"Runtime: {end_time - start_time:.2f} seconds")
    print("=" * 80)

run_analysis(INPUT_FILE)