# -*- coding: utf-8 -*-
"""Task2- M1 B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B1aznHBtV-mpgyGXOTIHQd7aJvAGHVY

### 2. Pandas Descriptive Statistics and Grouped Analysis


This script analyzes a CSV dataset using Pandas to compute dataset-level and column-level statistics.It calculates metrics for numeric and categorical columns and handles missing values and mixed data types.
It also performs grouped analysis (e.g., by page_id and page_id + ad_id) to compare patterns across groups. The script includes error handling to manage malformed CSV rows and ensure successful data loading.
"""

# Pandas Descriptive Statistics + Grouped Analysis
# This script analyzes CSV datasets using Pandas.
# It computes dataset-level, column-level, and grouped statistics.
# It also handles malformed CSV rows using the Python parser.

import pandas as pd
import ast
import os
import time

# =========================
# CONFIG
# =========================

INPUT_FILE = "/content/2024_fb_ads_president_scored_anon.csv"  # change this if needed
MAX_GROUPS_TO_DISPLAY = 3
TOP_N_VALUES = 5
DIVIDER = "-" * 80


# =========================
# HELPER FUNCTIONS
# =========================

def is_missing_series(series):
    return series.isna() | series.astype(str).str.strip().isin(
        ["", "nan", "NaN", "None", "N/A", "NA", "null", "NULL"]
    )


def parse_range_value(value):
    if pd.isna(value):
        return None

    text = str(value).strip()

    # Try normal numeric first
    try:
        return float(
            text.replace(",", "")
                .replace("$", "")
                .replace("%", "")
        )
    except:
        pass

    # Try dictionary-like range values
    if not (text.startswith("{") and text.endswith("}")):
        return None

    try:
        parsed = ast.literal_eval(text)

        if not isinstance(parsed, dict):
            return None

        lower = parsed.get("lower_bound")
        upper = parsed.get("upper_bound")

        lower = float(str(lower).replace(",", "")) if lower not in [None, ""] else None
        upper = float(str(upper).replace(",", "")) if upper not in [None, ""] else None

        if lower is not None and upper is not None:
            return (lower + upper) / 2
        elif lower is not None:
            return lower
        else:
            return None

    except:
        return None


def convert_possible_numeric(series):
    numeric = pd.to_numeric(
        series.astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .str.replace("%", "", regex=False),
        errors="coerce"
    )

    # If many values failed, try parsing dict/range strings
    if numeric.notna().mean() < 0.50:
        numeric = series.apply(parse_range_value)

    return pd.to_numeric(numeric, errors="coerce")


def infer_column_types(df):
    column_types = {}

    for col in df.columns:
        original_non_missing = ~is_missing_series(df[col])
        non_missing_count = original_non_missing.sum()

        if non_missing_count == 0:
            column_types[col] = "unknown"
            continue

        numeric_version = convert_possible_numeric(df[col])
        numeric_ratio = numeric_version.notna().sum() / non_missing_count

        if numeric_ratio >= 0.80:
            column_types[col] = "numeric"
        else:
            column_types[col] = "categorical"

    return column_types


def choose_grouping_columns(df):
    cols = set(df.columns)
    groupings = []

    # Facebook Ads
    if "page_id" in cols:
        groupings.append(["page_id"])

    if "page_id" in cols and "ad_id" in cols:
        groupings.append(["page_id", "ad_id"])

    # Facebook Posts
    if "page_id" in cols and "post_id" in cols:
        groupings.append(["page_id", "post_id"])

    # Twitter/X datasets
    if "account_id" in cols:
        groupings.append(["account_id"])
    elif "author_id" in cols:
        groupings.append(["author_id"])
    elif "username" in cols:
        groupings.append(["username"])
    elif "handle" in cols:
        groupings.append(["handle"])

    # Remove duplicate groupings
    unique_groupings = []
    for g in groupings:
        if g not in unique_groupings:
            unique_groupings.append(g)

    return unique_groupings


# =========================
# READING DATA
# =========================

def read_csv_safely(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    try:
        df = pd.read_csv(
            file_path,
            encoding="utf-8-sig",
            low_memory=False
        )
        print("CSV loaded using default Pandas C engine.")

    except pd.errors.ParserError:
        print("ParserError found. Retrying with Python engine and skipping malformed rows.")

        df = pd.read_csv(
            file_path,
            encoding="utf-8-sig",
            engine="python",
            on_bad_lines="skip"
        )

        print("CSV loaded using Python engine.")
        print("Malformed rows were skipped.")

    return df


# =========================
# PRINT FUNCTIONS
# =========================

def print_dataset_summary(df, column_types):
    print("\n" + DIVIDER)
    print("DATASET OVERALL SUMMARY")
    print(DIVIDER)

    print(f"Row count    : {len(df):,}")
    print(f"Column count : {len(df.columns):,}")

    print("\nMissing values per column:")
    for col in df.columns:
        missing = is_missing_series(df[col]).sum()
        pct = missing / len(df) * 100 if len(df) else 0
        print(f"  {col:<45} {missing:>8,} ({pct:5.1f}%)")

    print("\nInferred data types:")
    for col in df.columns:
        print(f"  {col:<45} {column_types[col]}")


def print_numeric_stats(df, col, indent=""):
    numeric = convert_possible_numeric(df[col]).dropna()
    missing = len(df) - len(numeric)

    print(f"\n{indent}{col} [numeric]")

    if numeric.empty:
        print(f"{indent}  No valid numeric values.")
        return

    print(f"{indent}  count   : {numeric.count():,}")
    print(f"{indent}  missing : {missing:,}")
    print(f"{indent}  mean    : {numeric.mean():,.2f}")
    print(f"{indent}  min     : {numeric.min():,.2f}")
    print(f"{indent}  max     : {numeric.max():,.2f}")
    print(f"{indent}  std dev : {numeric.std(ddof=0):,.2f}")
    print(f"{indent}  median  : {numeric.median():,.2f}")


def print_categorical_stats(df, col, indent=""):
    series = df[col]
    non_missing = series[~is_missing_series(series)].astype(str).str.strip()
    missing = len(df) - len(non_missing)

    print(f"\n{indent}{col} [categorical]")
    print(f"{indent}  count          : {len(non_missing):,}")
    print(f"{indent}  missing        : {missing:,}")
    print(f"{indent}  unique values  : {non_missing.nunique():,}")

    if len(non_missing) == 0:
        print(f"{indent}  mode           : N/A")
        print(f"{indent}  mode frequency : 0")
        return

    value_counts = non_missing.value_counts()

    print(f"{indent}  mode           : {value_counts.index[0]}")
    print(f"{indent}  mode frequency : {value_counts.iloc[0]:,}")
    print(f"{indent}  top 5 values   :")

    for value, count in value_counts.head(TOP_N_VALUES).items():
        value = str(value)
        if len(value) > 65:
            value = value[:62] + "..."
        print(f"{indent}    {value:<65} {count:,}")


def print_column_statistics(df, column_types):
    print("\n" + DIVIDER)
    print("COLUMN-LEVEL STATISTICS")
    print(DIVIDER)

    for col in df.columns:
        if column_types[col] == "numeric":
            print_numeric_stats(df, col)
        else:
            print_categorical_stats(df, col)


# =========================
# PANDAS DESCRIBE
# =========================

def print_pandas_describe(df, column_types):
    print("\n" + DIVIDER)
    print("PANDAS DESCRIBE OUTPUT")
    print(DIVIDER)

    numeric_df = pd.DataFrame()

    for col in df.columns:
        if column_types[col] == "numeric":
            numeric_df[col] = convert_possible_numeric(df[col])

    print("\nNumeric describe:")
    if not numeric_df.empty:
        print(numeric_df.describe())
    else:
        print("No numeric columns found.")

    categorical_cols = [col for col in df.columns if column_types[col] != "numeric"]

    print("\nCategorical describe:")
    if categorical_cols:
        print(df[categorical_cols].astype(str).describe())
    else:
        print("No categorical columns found.")


# =========================
# GROUPED ANALYSIS
# =========================

def print_grouped_analysis(df, group_cols, column_types):
    print("\n" + DIVIDER)
    print(f"GROUPED ANALYSIS BY: {', '.join(group_cols)}")
    print(DIVIDER)

    for col in group_cols:
        if col not in df.columns:
            print(f"Skipping group because column missing: {col}")
            return

    grouped = df.groupby(group_cols, dropna=False)
    group_sizes = grouped.size().sort_values(ascending=False)

    print(f"Total groups found: {len(group_sizes):,}")

    print("\nTop groups by row count:")
    print(group_sizes.head(10))

    print(f"\nShowing detailed statistics for top {MAX_GROUPS_TO_DISPLAY} groups only.")

    top_group_keys = group_sizes.head(MAX_GROUPS_TO_DISPLAY).index

    for key in top_group_keys:
        if len(group_cols) == 1:
            group_df = df[df[group_cols[0]] == key]
        else:
            key_tuple = key if isinstance(key, tuple) else (key,)
            mask = pd.Series(True, index=df.index)

            for col, value in zip(group_cols, key_tuple):
                mask &= df[col] == value

            group_df = df[mask]

        print("\n" + "=" * 70)
        print(f"GROUP: {key}")
        print(f"ROWS : {len(group_df):,}")
        print("=" * 70)

        for col in df.columns:
            if column_types[col] == "numeric":
                print_numeric_stats(group_df, col, indent="  ")
            else:
                print_categorical_stats(group_df, col, indent="  ")


# =========================
# MAIN
# =========================

def run_pandas_analysis(file_path):
    start_time = time.time()

    print("\n" + "=" * 80)
    print("PANDAS DESCRIPTIVE STATISTICS + GROUPED ANALYSIS")
    print("=" * 80)
    print(f"Input file: {file_path}")

    df = read_csv_safely(file_path)

    print(f"Loaded rows   : {len(df):,}")
    print(f"Loaded columns: {len(df.columns):,}")

    column_types = infer_column_types(df)

    print_dataset_summary(df, column_types)
    print_column_statistics(df, column_types)
    print_pandas_describe(df, column_types)

    groupings = choose_grouping_columns(df)

    if groupings:
        for group_cols in groupings:
            print_grouped_analysis(df, group_cols, column_types)
    else:
        print("\nNo sensible grouping columns found for this dataset.")

    end_time = time.time()

    print("\n" + "=" * 80)
    print("PANDAS ANALYSIS COMPLETE")
    print(f"Runtime: {end_time - start_time:.2f} seconds")
    print("=" * 80)


# =========================
# RUN
# =========================

run_pandas_analysis(INPUT_FILE)